export const actionTypes = {
    ADD_TODO: 'ADD_TODO',
    FETCH_TODOS: 'FETCH_TODOS',
    UPDATE_TODO: 'UPDATE_TODO',
    DELETE_TODO: 'DELETE_TODO',
    SORT_TODOS: 'SORT_TODOS',
    UPDATE_RECENT_TODO: 'UPDATE_RECENT_TODO',
    FETCH_FIRST_TEN_TODOS_SUCCESS: 'FETCH_FIRST_TEN_TODOS_SUCCESS',
    FETCH_RECENT_TEN_TODOS_SUCCESS: 'FETCH_RECENT_TEN_TODOS_SUCCESS'
};